config/routes.rb
Rails.application.routes.draw do
  root to: 'subs#index'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create] do
    resources :comments, only: [:new]
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :text             not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  parent_comment_id :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Comment < ActiveRecord::Base
  after_initialize :fetch_post_id
  validates :content, :author, :post, presence: true
  
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  belongs_to(
    :post,
    class_name: "Post",
    foreign_key: :post_id,
    primary_key: :id
  )
  
  belongs_to(
    :parent,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  )
  
  has_many(
    :children,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  )
  
  def fetch_post_id
    unless self.persisted?
      self.post_id = parent.post_id if self.parent
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new   
    @comment = Comment.new(
      post_id: params[:post_id], 
      parent_comment_id: params[:comment_id]
    )
    
  end
  
  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end
  
  private
    def comment_params
      params.require(:comment).permit([:content, :post_id, :parent_comment_id])
    end
end

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>

<%= comment.author.username %> at <%= time_ago_in_words(comment.created_at) %>

<%= link_to "Add a Comment!", new_comment_comment_url(comment) %>

<ul>
<% @all_comments[comment.id].each do |child| %>
  <li>
    <%= render 'comments/comment', comment: child %>
  </li>
<% end %>
</ul>

app/views/comments/new.html.erb
<form action="<%= comments_url %>" method="POST">
  <input type="hidden" 
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <textarea name="comment[content]" id="comment[content]"><%= @comment.content %></textarea>
  <input type="hidden"
          name="comment[post_id]"
          value="<%= @comment.post_id %>">
  <input type="hidden"
         name="comment[parent_comment_id]"
         value="<%= @comment.parent_comment_id %>">
  <input type="submit" value="Post comment!">
</form>