config/routes.rb
Rails.application.routes.draw do
  root to: 'subs#index'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create] do
    resources :comments, only: [:new]
  end
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string(255)      not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Sub < ActiveRecord::Base
  validates :title, :moderator, presence: true
  validates :title, uniqueness: true
  
  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id
  )
  
  has_many(
    :post_subs,
    class_name: "PostSub",
    foreign_key: :sub_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  has_many(
    :posts,
    through: :post_subs,
    source: :post
  )
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :check_sub_ownership, only: [:edit, :update]
  
  def index
    @subs = Sub.all
  end
  
  def show
    @sub = Sub.find(params[:id])
  end
  
  def new
    @sub = Sub.new
  end
  
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  
  def edit
    @sub = Sub.find(params[:id])
  end
  
  def update
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end
  
  def destroy
    Sub.destroy!(params[:id])
    redirect_to user_url(current_user)
  end
  
  private
    def sub_params
      params.require(:sub).permit([:title, :description])
    end
    
    def check_sub_ownership
      redirect_to session_url unless current_user
      unless Sub.find(params[:id]).moderator_id == current_user.id
        redirect_to sub_url(params[:id])
      end
    end
end

app/views/subs/_form.html.erb
<% if @sub.persisted? %>
  <% action = sub_url(@sub) %>
  <% button_text =  "Update #{@sub.title}" %>
<% else %>
  <% action = subs_url %>
  <% button_text =  "Create sub!" %>
<% end %>

<form action="<%= action %>" method="POST">
  <% if @sub.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  
  <label for="title">Title</label>
  <input type="text" name="sub[title]" value="<%= @sub.title %>">
  <label for="description">Description</label>
  <textarea name="sub[description]">
    <%= @sub.description%>
  </textarea>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/subs/edit.html.erb
<h1>Edit <%= @sub.title %></h1>

<%= render 'form' %>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
  <% @subs.each do |sub| %>
    <li>
      <%= link_to sub.title, sub_url(sub) %>
    </li>
  <% end %>
</ul>

<%= link_to 'Create a new sub', new_sub_url %>

app/views/subs/new.html.erb
<h1>Make a new sub!</h1>

<%= render 'form' %>

app/views/subs/show.html.erb
<h1>b_r/<%= @sub.title %></h1>

<div>
  <%= link_to "Post something new", new_post_url %>
</div>

<ul>
  <% @sub.posts.each do |post| %>
    <li>
      <%= link_to post.title, post_url(post) %>
    </li>
  <% end %>
</ul>