config/routes.rb
Rails.application.routes.draw do
  root to: 'subs#index'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create] do
    resources :comments, only: [:new]
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  url        :string(255)
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  has_many(
    :post_subs,
    class_name: "PostSub",
    foreign_key: :post_id,
    primary_key: :id,
    dependent: :destroy,
    inverse_of: :post
  )
  
  has_many(
    :subs,
    through: :post_subs,
    source: :sub
  )
  
  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :post_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  has_many(
    :top_level_comments,
    -> { where(parent_comment_id: nil) },
    class_name: "Comment",
    foreign_key: :post_id,
    primary_key: :id
  )
  
  def comments_by_parent_id
    comments_by_parent = Hash.new([])
    self.comments.includes(:author).each do |comment|
      comments_by_parent[comment.parent_comment_id] += [comment]
    end
    comments_by_parent
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_post_authorship, :only  => [:edit, :update, :destroy]
  
  def show
    @post = Post.find(params[:id])
    @all_comments = @post.comments_by_parent_id
  end
  
  def new
    @post = Post.new
  end
  
  def ensure_post_authorship
    return redirect_to new_session_url if current_user.nil?
    unless Post.find(params[:id]).author_id == current_user.id
      redirect_to post_url(params[:id])
    end
  end
  
  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    Post.destroy(params[:id])
    redirect_to user_url(current_user)
  end
  
  private
    def post_params
      params.require(:post)
      .permit(:title, :description, :content, :url, sub_ids: [])
    end
  
end

app/views/posts/_form.html.erb
<% if @post.persisted? %>
  <% action = post_url(@post) %>
  <% button_text =  "Update #{@post.title}" %>
<% else %>
  <% action = posts_url %>
  <% button_text =  "Create post!" %>
<% end %>

<form action="<%= action %>" method="POST">
  <% if @post.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  
  <label for="title">Title</label>
  <input type="text" name="post[title]" value="<%= @post.title %>">
  
  <label for="post_url">URL</label>
  <input type="text" name="post[url]" value="<%= @post.url %>">
  
  <label for="post_content">Content</label>
  <textarea name="post[content]">
    <%= @post.content%>
  </textarea>
  
  <ul>
    <% Sub.all.each do |sub| %>
      <li>
        <label for="<%= sub %>"><%= sub.title %></label>
        <input type="checkbox" 
               name="post[sub_ids][]" 
               id="<%= sub.id %>"
               value="<%= sub.id %>"
          <%= "checked" if @post.sub_ids.include?(sub.id) %>>
      </li>
    <% end %>
  </ul>
  
  <input type="submit" value="<%= button_text %>">
</form>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/new.html.erb
<h1>New Post!</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<% if @post.url %>
  <h1>
    <%= link_to @post.title, @post.url %>
  </h1>
<% else %>
  <h1><%= @post.title %></h1>
<% end %>

<% @post.subs.each do |sub| %>
  <%= link_to sub.title, sub_url(sub) %>
<% end %>

<p><%= @post.content %></p>

<% if current_user && @post.author_id == current_user.id%>
  <%= link_to "Edit post", edit_post_url(@post) %>
  <%= link_to "Delete Unfit Post", post_url(@post), :method  => :delete %>
<% end %>

<%= link_to "Add a comment!", new_post_comment_url(@post) %>

<ul>
  <% @all_comments[nil].each do |comment| %> 
    <li>
      <%= render "comments/comment", comment: comment %>
    </li>
  <% end %>
</ul>